version: '3.9'

services:
  db:
    image: postgres:16
    container_name: todolist-postgres
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todolist
    ports:
      - "5432:5432"
    volumes:
      - ./init-db/thegridlist.sql:/docker-entrypoint-initdb.d/thegridlist.sql
    networks:
      - todolist-net

  backend:
    build: ./backend
    container_name: todolist-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/todolist
      SPRING_DATASOURCE_USERNAME: todo_user
      SPRING_DATASOURCE_PASSWORD: secret
    networks:
      - todolist-net

networks:
  todolist-net:
    driver: bridge
